
const express=require("express"),http=require("http"),{Server}=require("socket.io");
const app=express(),server=http.createServer(app),io=new Server(server);app.use(express.static("public"));
const rooms=new Map(),G=["coup","carcassonne","oriflamme"],R=["Duke","Duke","Duke","Assassin","Assassin","Assassin","Captain","Captain","Captain","Ambassador","Ambassador","Ambassador","Contessa","Contessa","Contessa"],RU={Duke:"Герцог",Assassin:"Убийца",Captain:"Капитан",Ambassador:"Посол",Contessa:"Графиня"},CLAIM={tax:"Duke",steal:"Captain",exchange:"Ambassador",assassinate:"Assassin"},T=["road","city","field","monastery","road","city","field","road","city","field","monastery","road","city","field","road","city","field","road","city","field"];
const sh=a=>[...a].sort(()=>Math.random()-.5),code=()=>Math.random().toString(36).slice(2,7).toUpperCase(),alive=p=>p?.cards?.some(c=>c.alive),ids=p=>p.cards.map((c,i)=>c.alive?i:-1).filter(i=>i>=0);
function pub(p,self){return{id:p.id,name:p.name,coins:p.coins||0,score:p.score||0,meeples:p.meeples||0,alive:alive(p),cards:(p.cards||[]).map(c=>c.alive?(self?(c.role||c.name):"hidden"):"lost")}}
function snap(r,id){return{code:r.code,game:r.game,host:r.host,started:r.started,turn:r.turn,pending:r.pending,log:r.log.slice(-40),players:r.players.map(p=>pub(p,p.id===id)),me:pub(r.players.find(p=>p.id===id),true),winner:r.winner,board:r.board,currentTile:r.currentTile,phase:r.phase}}
const send=r=>r.players.forEach(p=>io.to(p.id).emit("state",snap(r,p.id))),log=(r,x)=>r.log.push(x);
function next(r){for(let n=1;n<=r.players.length;n++){let i=(r.turn+n)%r.players.length;if(alive(r.players[i])||r.game!=="coup"){r.turn=i;return}}}
function end(r){if(r.game==="coup"){let a=r.players.filter(alive);if(a.length<=1){r.started=false;r.winner=a[0]?.name;log(r,`🏆 ${r.winner} победил!`);return true}}if(r.game==="carcassonne"&&!r.deck.length&&!r.currentTile){r.started=false;r.winner=[...r.players].sort((a,b)=>b.score-a.score)[0]?.name;log(r,`🏆 ${r.winner} победил!`);return true}return false}
function start(r){r.winner=null;r.pending=null;r.turn=0;r.started=true;
 if(r.game==="coup"){let d=sh(R).map(role=>({role,alive:true}));r.players.forEach(p=>{p.coins=2;p.score=0;p.cards=[d.pop(),d.pop()]}),r.deck=d;log(r,"🎲 Переворот начался.")}
 if(r.game==="carcassonne"){r.players.forEach(p=>{p.score=0;p.meeples=7;p.cards=[]});r.deck=sh(T).map(type=>({type}));r.board=[{x:0,y:0,type:r.deck.pop().type,meeple:false,owner:null}];r.currentTile=r.deck.pop();log(r,"🏰 Каркассон начался.")}
 if(r.game==="oriflamme"){r.players.forEach(p=>{p.score=0;p.coins=6;p.cards=[]});r.deck=sh(["Вельможа","Шпион","Убийца","Дипломат","Засада","Саботажник","Наследник","Страж"]).map(name=>({name,id:Math.random()}));r.phase="plan";log(r,"⚔️ Орифламма началась.")}
 send(r)}
function lose(r,p){let a=ids(p);if(a.length){p.cards[a[0]].alive=false;log(r,`☠️ ${p.name} потерял влияние.`)}}
function finishCoup(r){let q=r.pending,a=r.players.find(p=>p.id===q.actor),t=r.players.find(p=>p.id===q.target);if(q.action==="income")a.coins++;if(q.action==="foreignAid")a.coins+=2;if(q.action==="tax")a.coins+=3;if(q.action==="steal"&&t){let n=Math.min(2,t.coins);t.coins-=n;a.coins+=n}if(q.action==="assassinate"&&t){a.coins-=3;lose(r,t)}if(q.action==="coup"&&t){a.coins-=7;lose(r,t)}if(q.action==="exchange"){let h=a.cards.filter(c=>c.alive),d=r.deck.splice(0,2),p=sh([...h,...d]);a.cards=a.cards.map(c=>c.alive?p.pop():c);r.deck.push(...p)}r.pending=null;if(!end(r))next(r);send(r)}
function actionCoup(r,a,action,target){if(a.coins>=10&&action!=="coup")return log(r,"⚠️ При 10+ монетах нужно делать переворот."),send(r);let t=target?r.players.find(p=>p.id===target):null;if(["steal","assassinate","coup"].includes(action)&&(!t||t===a||!alive(t)))return;if(action==="coup"&&a.coins<7||action==="assassinate"&&a.coins<3)return;let claim=CLAIM[action];r.pending={actor:a.id,target:t?.id,action,claim,blockedBy:null,blockClaim:null};log(r,`🎭 ${a.name} выбирает действие.`);if(!claim)return finishCoup(r);send(r);setTimeout(()=>{if(r.pending?.actor===a.id)finishCoup(r)},20000)}
function challenge(r,id){let q=r.pending;if(!q?.claim)return;let a=r.players.find(p=>p.id===q.actor),c=r.players.find(p=>p.id===id);if(a.cards.some(x=>x.alive&&x.role===q.claim)){lose(r,c);let i=a.cards.findIndex(x=>x.alive&&x.role===q.claim);a.cards[i].alive=false;r.deck.push({role:q.claim,alive:true});a.cards[i]=r.deck.pop()||{role:q.claim,alive:true};log(r,`⚔️ ${a.name} доказал ${RU[q.claim]}.`)}else{lose(r,a);log(r,`❌ ${a.name} блефовал.`)}r.pending=null;if(!end(r))next(r);send(r)}
function block(r,id,claim){let q=r.pending,b=r.players.find(p=>p.id===id);if(!q||!b)return;let ok=q.action==="foreignAid"&&claim==="Duke"||q.action==="steal"&&(claim==="Captain"||claim==="Ambassador")||q.action==="assassinate"&&claim==="Contessa";if(!ok)return;q.blockedBy=id;q.blockClaim=claim;q.claim=null;log(r,`🛡️ ${b.name} блокирует действие.`);send(r);setTimeout(()=>{if(r.pending?.blockedBy===id)finishCoup(r)},20000)}
function placeC(r,p,x,y){if(!r.currentTile||r.board.some(t=>t.x===x&&t.y===y)||!r.board.some(t=>Math.abs(t.x-x)+Math.abs(t.y-y)===1))return;let t=r.currentTile;r.board.push({x,y,type:t.type,meeple:false,owner:null});r.currentTile=r.deck.pop();p.score+=t.type==="city"?2:t.type==="monastery"?3:t.type==="road"?1:0;if(p.meeples&&Math.random()>.45){r.board[r.board.length-1].meeple=true;r.board[r.board.length-1].owner=p.id;p.meeples--}log(r,`🧩 ${p.name} поставил ${t.type}.`);if(!end(r))next(r);send(r)}
function playO(r,p,id){let i=r.deck.findIndex(c=>c.id===id);if(i<0||r.turn!==r.players.indexOf(p))return;let c=r.deck.splice(i,1)[0];p.cards.push({name:c.name,id:c.id,owner:p.id,alive:true});p.score++;log(r,`🃏 ${p.name} тайно выложил карту.`);next(r);if(r.turn===0){r.phase="reveal";setTimeout(()=>{let all=r.players.flatMap(x=>x.cards.filter(c=>c.alive));if(all.length){let c=all[Math.floor(Math.random()*all.length)],o=r.players.find(x=>x.id===c.owner);o.score+=c.name==="Вельможа"?2:1;c.alive=false;log(r,`✨ Раскрыта карта ${c.name}.`)}r.players.forEach(x=>x.cards=[]);r.phase="plan";send(r)},800)}send(r)}
io.on("connection",s=>{
 s.on("create",({name,game},cb)=>{if(!G.includes(game))return cb({ok:false,error:"Игра не найдена"});let c=code(),r={code:c,game,host:s.id,players:[{id:s.id,name:(name||"Игрок").slice(0,20),cards:[],coins:0,score:0,meeples:0}],started:false,turn:0,pending:null,deck:[],board:[],log:[],winner:null};rooms.set(c,r);s.join(c);cb({ok:true,code:c});send(r)});
 s.on("join",({name,code:c},cb)=>{let r=rooms.get(String(c||"").toUpperCase());if(!r)return cb({ok:false,error:"Комната не найдена"});if(r.started)return cb({ok:false,error:"Игра уже началась"});if(r.players.length>=6)return cb({ok:false,error:"Максимум 6 игроков"});r.players.push({id:s.id,name:(name||"Игрок").slice(0,20),cards:[],coins:0,score:0,meeples:0});s.join(r.code);cb({ok:true,code:r.code});send(r)});
 s.on("start",()=>{for(let r of rooms.values())if(r.players.some(p=>p.id===s.id)&&r.host===s.id&&!r.started&&r.players.length>=2)start(r)});
 s.on("action",({action,targetId})=>{for(let r of rooms.values())if(r.players.some(p=>p.id===s.id)){if(r.game==="coup"&&r.started&&!r.pending&&r.players[r.turn]?.id===s.id)actionCoup(r,r.players[r.turn],action,targetId);return}});
 s.on("challenge",()=>{for(let r of rooms.values())if(r.players.some(p=>p.id===s.id)){challenge(r,s.id);return}});
 s.on("block",({claim})=>{for(let r of rooms.values())if(r.players.some(p=>p.id===s.id)){block(r,s.id,claim);return}});
 s.on("carcassonnePlace",({x,y})=>{for(let r of rooms.values())if(r.players.some(p=>p.id===s.id)&&r.game==="carcassonne"){let p=r.players.find(p=>p.id===s.id);if(r.started&&r.turn===r.players.indexOf(p))placeC(r,p,x,y);return}});
 s.on("oriflammePlay",({cardId})=>{for(let r of rooms.values())if(r.players.some(p=>p.id===s.id)&&r.game==="oriflamme"){let p=r.players.find(p=>p.id===s.id);if(r.started)playO(r,p,cardId);return}});
 s.on("disconnect",()=>{for(let r of rooms.values()){let i=r.players.findIndex(p=>p.id===s.id);if(i<0)continue;r.players.splice(i,1);if(r.host===s.id)r.host=r.players[0]?.id;if(!r.players.length)rooms.delete(r.code);else send(r)}})
});
server.listen(process.env.PORT||3000);
